type Token {
  id: ID!
  symbol: String!
  name: String!
  decimals: Int!
  poolCount: Int!
  txCount: Int!
  volume: BigDecimal!
  whitelistPoolIds: [String!]!
}

type LendingToken {
  id: ID!
  symbol: String!
  name: String!
  decimals: Int!
  pool: Pool! @index
  tokenType: Int!
}

type Pool {
  id: ID!
  tokenX: Token!
  tokenY: Token!
  name: String!
  reserveX: BigInt!
  reserveY: BigInt!
  tokenXPrice: BigDecimal!
  tokenYPrice: BigDecimal!
  totalAssets: [BigInt!]!
  totalShares: [BigInt!]!
  createdAtTimestamp: BigInt!
  createdAtBlockNumber: BigInt!
  txCount: Int!
  depositCount: Int!
  withdrawCount: Int!
  borrowCount: Int!
  repayCount: Int!
  transferCount: Int!
  swapCount: Int!
  syncCount: Int!
  liquidateCount: Int!
  interestAccruedCount: Int!
  burnBadDebtCount: Int!
  volumeTokenX: BigDecimal!
  volumeTokenY: BigDecimal!
  positionCount: Int!
  lendingTokens: [LendingToken!]! @derivedFrom(field: "pool")
  positions: [Position!]! @derivedFrom(field: "pool")
  deposits: [Deposit!]! @derivedFrom(field: "pool")
  withdraws: [Withdraw!]! @derivedFrom(field: "pool")
  borrows: [Borrow!]! @derivedFrom(field: "pool")
  repays: [Repay!]! @derivedFrom(field: "pool")
  transfers: [Transfer!]! @derivedFrom(field: "pool")
  swaps: [Swap!]! @derivedFrom(field: "pool")
  syncs: [Sync!]! @derivedFrom(field: "pool")
  liquidates: [Liquidate!]! @derivedFrom(field: "pool")
  interestAccruals: [InterestAccrued!]! @derivedFrom(field: "pool")
  burnBadDebts: [BurnBadDebt!]! @derivedFrom(field: "pool")
}

type User {
  id: ID!
  positionCount: Int!
  positions: [Position!]! @derivedFrom(field: "user")
  swapCount: Int!
  liquidationCount: Int!
  swaps: [Swap!]! @derivedFrom(field: "from")
  liquidations: [Liquidate!]! @derivedFrom(field: "borrower")
  depositCount: Int!
  deposits: [Deposit!]! @derivedFrom(field: "user")
  withdrawCount: Int!
  withdraws: [Withdraw!]! @derivedFrom(field: "user")
  borrowCount: Int!
  borrows: [Borrow!]! @derivedFrom(field: "user")
  repayCount: Int!
  repays: [Repay!]! @derivedFrom(field: "user")
  transferredCount: Int!
  transfers: [Transfer!]! @derivedFrom(field: "sender")
  receivedCount: Int!
  receives: [Transfer!]! @derivedFrom(field: "receiver")
}

type Position {
  id: ID!
  user: User!
  pool: Pool!
  hash: String!
  blockNumber: BigInt!
  timestamp: BigInt!
  assets: [BigInt!]!
  shares: [BigInt!]!
  principal: BigInt!
  depositCount: Int!
  deposits: [Deposit!]! @derivedFrom(field: "position")
  withdrawCount: Int!
  withdraws: [Withdraw!]! @derivedFrom(field: "position")
  borrowCount: Int!
  borrows: [Borrow!]! @derivedFrom(field: "position")
  repayCount: Int!
  repays: [Repay!]! @derivedFrom(field: "position")
  transferredCount: Int!
  transfers: [Transfer!]! @derivedFrom(field: "senderPosition")
  receivedCount: Int!
  receives: [Transfer!]! @derivedFrom(field: "receiverPosition")
}

type Deposit {
  id: ID!
  hash: String!
  logIndex: Int!
  blockNumber: BigInt!
  timestamp: BigInt!
  user: User!
  from: User!
  pool: Pool!
  position: Position!
  asset: LendingToken!
  amount: BigInt!
  shares: BigInt
}

type Withdraw {
  id: ID!
  hash: String!
  logIndex: Int!
  blockNumber: BigInt!
  timestamp: BigInt!
  user: User!
  from: User!
  pool: Pool!
  position: Position!
  asset: LendingToken!
  amount: BigInt!
  shares: BigInt
}

type Borrow {
  id: ID!
  hash: String!
  logIndex: Int!
  blockNumber: BigInt!
  timestamp: BigInt!
  user: User!
  from: User!
  pool: Pool!
  position: Position!
  asset: LendingToken!
  amount: BigInt!
  shares: BigInt!
}

type Repay {
  id: ID!
  hash: String!
  logIndex: Int!
  blockNumber: BigInt!
  timestamp: BigInt!
  user: User!
  from: User!
  pool: Pool!
  position: Position!
  asset: LendingToken!
  amount: BigInt!
  shares: BigInt!
}

type Transfer {
  id: ID!
  hash: String!
  logIndex: Int!
  blockNumber: BigInt!
  timestamp: BigInt!
  sender: User!
  receiver: User!
  pool: Pool!
  senderPosition: Position!
  receiverPosition: Position!
  asset: LendingToken!
  amount: BigInt!
  shares: BigInt!
}

type Swap {
  id: ID!
  hash: String!
  logIndex: Int!
  blockNumber: BigInt!
  timestamp: BigInt!
  pool: Pool!
  tokenX: Token!
  tokenY: Token!
  sender: User!
  from: User!
  to: User!
  amountXIn: BigInt!
  amountYIn: BigInt!
  amountXOut: BigInt!
  amountYOut: BigInt!
}

type Sync {
  id: ID!
  hash: String!
  logIndex: Int!
  blockNumber: BigInt!
  timestamp: BigInt!
  pool: Pool!
  reserveX: BigInt!
  reserveY: BigInt!
}

type Liquidate {
  id: ID!
  hash: String!
  logIndex: Int!
  blockNumber: BigInt!
  timestamp: BigInt!
  pool: Pool!
  borrower: User!
  liquidator: User!
  seizedLAssets: BigInt!
  seizedXAssets: BigInt!
  seizedYAssets: BigInt!
  repayXAssets: BigInt!
  repayYAssets: BigInt!
  actualRepaidXAssets: BigInt!
  actualRepaidYAssets: BigInt!
  liquidationType: BigInt!
}

type InterestAccrued {
  id: ID!
  hash: String!
  logIndex: Int!
  blockNumber: BigInt!
  timestamp: BigInt!
  pool: Pool!
  reserveX: BigInt!
  reserveY: BigInt!
  depositXAssets: BigInt!
  depositYAssets: BigInt!
  borrowLAssets: BigInt!
  borrowXAssets: BigInt!
  borrowYAssets: BigInt!
}

type BurnBadDebt {
  id: ID!
  hash: String!
  logIndex: Int!
  blockNumber: BigInt!
  timestamp: BigInt!
  pool: Pool!
  borrower: User!
  tokenType: BigInt!
  badDebtAssets: BigInt!
  badDebtShares: BigInt!
}
