import { DEFAULT_TOKEN_BALANCES, ZERO_BI } from './constants'
import { convertTokenToDecimal, safeDiv, ZERO_BD } from './math'

export function createDefaultPool(
  poolId: string,
  tokenXId: string,
  tokenYId: string,
  name: string,
  createdAtTimestamp: bigint,
  createdAtBlockNumber: bigint,
) {
  return {
    id: poolId,
    tokenX_id: tokenXId,
    tokenY_id: tokenYId,
    name,
    reserveX: ZERO_BI,
    reserveY: ZERO_BI,
    tokenXPrice: ZERO_BD,
    tokenYPrice: ZERO_BD,
    totalAssets: [...DEFAULT_TOKEN_BALANCES],
    totalShares: [...DEFAULT_TOKEN_BALANCES],
    pendingProtocolInterestTxHash: undefined,
    createdAtTimestamp,
    createdAtBlockNumber,
    txCount: 0,
    depositCount: 0,
    withdrawCount: 0,
    borrowCount: 0,
    repayCount: 0,
    transferCount: 0,
    swapCount: 0,
    syncCount: 0,
    liquidateCount: 0,
    interestAccruedCount: 0,
    burnBadDebtCount: 0,
    volumeTokenX: ZERO_BI,
    volumeTokenY: ZERO_BI,
    swapFeesTokenX: ZERO_BI,
    swapFeesTokenY: ZERO_BI,
    swapFeesTokenL: ZERO_BI,
    grossInterestTokenX: ZERO_BI,
    grossInterestTokenY: ZERO_BI,
    grossInterestTokenL: ZERO_BI,
    grossInterestTokenLAsX: ZERO_BI,
    grossInterestTokenLAsY: ZERO_BI,
    protocolInterestTokenX: ZERO_BI,
    protocolInterestTokenY: ZERO_BI,
    protocolInterestTokenL: ZERO_BI,
    protocolInterestTokenLAsX: ZERO_BI,
    protocolInterestTokenLAsY: ZERO_BI,
    lpInterestTokenL: ZERO_BI,
    lpInterestTokenLAsX: ZERO_BI,
    lpInterestTokenLAsY: ZERO_BI,
    protocolFeesTokenX: ZERO_BI,
    protocolFeesTokenY: ZERO_BI,
    protocolFeesTokenL: ZERO_BI,
    protocolFeesTokenLAsX: ZERO_BI,
    protocolFeesTokenLAsY: ZERO_BI,
    initialLendingFeesTokenX: ZERO_BI,
    initialLendingFeesTokenY: ZERO_BI,
    initialLendingFeesTokenL: ZERO_BI,
    initialLendingFeesTokenLAsX: ZERO_BI,
    initialLendingFeesTokenLAsY: ZERO_BI,
    penaltiesTokenL: ZERO_BI,
    penaltiesTokenLAsX: ZERO_BI,
    penaltiesTokenLAsY: ZERO_BI,
    positionCount: 0,
    externalLiquidity: ZERO_BI,
  }
}

export function createDefaultPoolDayData(id: string, poolId: string, date: number) {
  return {
    id,
    pool_id: poolId,
    date,
    volumeTokenX: ZERO_BI,
    volumeTokenY: ZERO_BI,
    txCount: 0,
    swapCount: 0,
    swapFeesTokenX: ZERO_BI,
    swapFeesTokenY: ZERO_BI,
    swapFeesTokenL: ZERO_BI,
    grossInterestTokenX: ZERO_BI,
    grossInterestTokenY: ZERO_BI,
    grossInterestTokenL: ZERO_BI,
    grossInterestTokenLAsX: ZERO_BI,
    grossInterestTokenLAsY: ZERO_BI,
    protocolInterestTokenX: ZERO_BI,
    protocolInterestTokenY: ZERO_BI,
    protocolInterestTokenL: ZERO_BI,
    protocolInterestTokenLAsX: ZERO_BI,
    protocolInterestTokenLAsY: ZERO_BI,
    lpInterestTokenL: ZERO_BI,
    lpInterestTokenLAsX: ZERO_BI,
    lpInterestTokenLAsY: ZERO_BI,
    protocolFeesTokenX: ZERO_BI,
    protocolFeesTokenY: ZERO_BI,
    protocolFeesTokenL: ZERO_BI,
    protocolFeesTokenLAsX: ZERO_BI,
    protocolFeesTokenLAsY: ZERO_BI,
    initialLendingFeesTokenX: ZERO_BI,
    initialLendingFeesTokenY: ZERO_BI,
    initialLendingFeesTokenL: ZERO_BI,
    initialLendingFeesTokenLAsX: ZERO_BI,
    initialLendingFeesTokenLAsY: ZERO_BI,
    penaltiesTokenL: ZERO_BI,
    penaltiesTokenLAsX: ZERO_BI,
    penaltiesTokenLAsY: ZERO_BI,
  }
}

export function poolPriceFields(
  tokenX: { decimals: number },
  tokenY: { decimals: number },
  reserveXAssets: bigint,
  reserveYAssets: bigint,
) {
  const reserveX = convertTokenToDecimal(reserveXAssets, tokenX.decimals)
  const reserveY = convertTokenToDecimal(reserveYAssets, tokenY.decimals)
  return {
    reserveX: reserveXAssets,
    reserveY: reserveYAssets,
    tokenXPrice: safeDiv(reserveY, reserveX),
    tokenYPrice: safeDiv(reserveX, reserveY),
  }
}
